### PR TITLE
Initial Commit Landing Page

### PR DESCRIPTION
**Pull request by evs95**
Changes for this card #5 (Create Landing Page)

### CODE REVIEW

**Review by BinaryBitBytes — APPROVED** [review]
I see the HTML and CSS as well as the script.js. Looks good. CDNs are called in their correct positions. Nice work

**Review by YellowYam — COMMENTED** [review]
Looks good! That's an excellent starting document. I'll leave this comment and wait for Miles to approve it.

**Comment by BinaryBitBytes** [comment]
I approved in the changes approved

**Comment by YellowYam** [comment]
Merged!

**Pull request merged**
