### PR TITLE
designed wireframe for UX, added screenshot

### PR DESCRIPTION
**Pull request by BinaryBitBytes**
added the design to a png and pushed to my local branch BBB for approval and documentation.

### CODE REVIEW

**Review by YellowYam — COMMENTED** [review]
Excellent work!

**Comment by BinaryBitBytes** [comment]
> Excellent work!
Let me know when I need to start writing code for this. Let me know the requirements. will that code assignment be in the cards on the chart?

**Review by YellowYam — COMMENTED** [review]
The UI design looks more ergonomic. Your explanation for how to program the "cities nearby" section was brilliant.

**Review by YellowYam — APPROVED** [review]
Looks good, Miles.

**Pull request merged**
